// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.0
// source: follower/follower.proto

package follower

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FollowerClient is the client API for Follower service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FollowerClient interface {
	CreateNewFollowing(ctx context.Context, in *UserFollowingDto, opts ...grpc.CallOption) (*FollowerResponseDto, error)
	GetFollowerRecommendations(ctx context.Context, in *Id, opts ...grpc.CallOption) (*ListFollowingResponseDto, error)
	GetFollowings(ctx context.Context, in *Id, opts ...grpc.CallOption) (*ListFollowingResponseDto, error)
	GetFollowers(ctx context.Context, in *Id, opts ...grpc.CallOption) (*ListFollowingResponseDto, error)
	GetAllFromFollowingUsers(ctx context.Context, in *Id, opts ...grpc.CallOption) (*BlogListResponse, error)
}

type followerClient struct {
	cc grpc.ClientConnInterface
}

func NewFollowerClient(cc grpc.ClientConnInterface) FollowerClient {
	return &followerClient{cc}
}

func (c *followerClient) CreateNewFollowing(ctx context.Context, in *UserFollowingDto, opts ...grpc.CallOption) (*FollowerResponseDto, error) {
	out := new(FollowerResponseDto)
	err := c.cc.Invoke(ctx, "/Follower/CreateNewFollowing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followerClient) GetFollowerRecommendations(ctx context.Context, in *Id, opts ...grpc.CallOption) (*ListFollowingResponseDto, error) {
	out := new(ListFollowingResponseDto)
	err := c.cc.Invoke(ctx, "/Follower/GetFollowerRecommendations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followerClient) GetFollowings(ctx context.Context, in *Id, opts ...grpc.CallOption) (*ListFollowingResponseDto, error) {
	out := new(ListFollowingResponseDto)
	err := c.cc.Invoke(ctx, "/Follower/GetFollowings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followerClient) GetFollowers(ctx context.Context, in *Id, opts ...grpc.CallOption) (*ListFollowingResponseDto, error) {
	out := new(ListFollowingResponseDto)
	err := c.cc.Invoke(ctx, "/Follower/GetFollowers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followerClient) GetAllFromFollowingUsers(ctx context.Context, in *Id, opts ...grpc.CallOption) (*BlogListResponse, error) {
	out := new(BlogListResponse)
	err := c.cc.Invoke(ctx, "/Follower/GetAllFromFollowingUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FollowerServer is the server API for Follower service.
// All implementations must embed UnimplementedFollowerServer
// for forward compatibility
type FollowerServer interface {
	CreateNewFollowing(context.Context, *UserFollowingDto) (*FollowerResponseDto, error)
	GetFollowerRecommendations(context.Context, *Id) (*ListFollowingResponseDto, error)
	GetFollowings(context.Context, *Id) (*ListFollowingResponseDto, error)
	GetFollowers(context.Context, *Id) (*ListFollowingResponseDto, error)
	GetAllFromFollowingUsers(context.Context, *Id) (*BlogListResponse, error)
	mustEmbedUnimplementedFollowerServer()
}

// UnimplementedFollowerServer must be embedded to have forward compatible implementations.
type UnimplementedFollowerServer struct {
}

func (UnimplementedFollowerServer) CreateNewFollowing(context.Context, *UserFollowingDto) (*FollowerResponseDto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNewFollowing not implemented")
}
func (UnimplementedFollowerServer) GetFollowerRecommendations(context.Context, *Id) (*ListFollowingResponseDto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowerRecommendations not implemented")
}
func (UnimplementedFollowerServer) GetFollowings(context.Context, *Id) (*ListFollowingResponseDto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowings not implemented")
}
func (UnimplementedFollowerServer) GetFollowers(context.Context, *Id) (*ListFollowingResponseDto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowers not implemented")
}
func (UnimplementedFollowerServer) GetAllFromFollowingUsers(context.Context, *Id) (*BlogListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllFromFollowingUsers not implemented")
}
func (UnimplementedFollowerServer) mustEmbedUnimplementedFollowerServer() {}

// UnsafeFollowerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FollowerServer will
// result in compilation errors.
type UnsafeFollowerServer interface {
	mustEmbedUnimplementedFollowerServer()
}

func RegisterFollowerServer(s grpc.ServiceRegistrar, srv FollowerServer) {
	s.RegisterService(&Follower_ServiceDesc, srv)
}

func _Follower_CreateNewFollowing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFollowingDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowerServer).CreateNewFollowing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Follower/CreateNewFollowing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowerServer).CreateNewFollowing(ctx, req.(*UserFollowingDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _Follower_GetFollowerRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowerServer).GetFollowerRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Follower/GetFollowerRecommendations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowerServer).GetFollowerRecommendations(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _Follower_GetFollowings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowerServer).GetFollowings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Follower/GetFollowings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowerServer).GetFollowings(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _Follower_GetFollowers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowerServer).GetFollowers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Follower/GetFollowers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowerServer).GetFollowers(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _Follower_GetAllFromFollowingUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowerServer).GetAllFromFollowingUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Follower/GetAllFromFollowingUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowerServer).GetAllFromFollowingUsers(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

// Follower_ServiceDesc is the grpc.ServiceDesc for Follower service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Follower_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Follower",
	HandlerType: (*FollowerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNewFollowing",
			Handler:    _Follower_CreateNewFollowing_Handler,
		},
		{
			MethodName: "GetFollowerRecommendations",
			Handler:    _Follower_GetFollowerRecommendations_Handler,
		},
		{
			MethodName: "GetFollowings",
			Handler:    _Follower_GetFollowings_Handler,
		},
		{
			MethodName: "GetFollowers",
			Handler:    _Follower_GetFollowers_Handler,
		},
		{
			MethodName: "GetAllFromFollowingUsers",
			Handler:    _Follower_GetAllFromFollowingUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "follower/follower.proto",
}
